server:
  port: 8082

spring:
  application:
    name: product-consumer

eureka:
  instance:
    prefer-ip-address: true # 使用自身ip地址注册至Eureka注册中心
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
