server:
  port: 8091

spring:
  application:
    name: product-provider

eureka:
  instance:
    prefer-ip-address: true # 使用服务的ip地址注册至Eureka注册中心
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
